### PR TITLE
Fix memory leak with opera notifications

### LINKED ISSUE #113: Notifications Hang system and use 100% CPU [$65]
When ever I get a notification from the daemon it causes the computer to slow way down and when I check the processes I see that the is using 100% of the cpu. The computer will return to normal after a sigterm the process. Most of my notifications come from Opera browser I don't know if there is a related compatibility issue. Screenshot -> https://www.dropbox.com/s/rwpa95enw9syegy/mate-notification-daemon-crash.png?raw=1
## 

<bountysource-plugin>

---
There is a **[$65 open bounty](https://www.bountysource.com/issues/38648165-notifications-hang-system-and-use-100-cpu?utm_campaign=plugin&utm_content=tracker%2F1172660&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1172660&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by snaiperskaya96**
Fixes #113

### CODE REVIEW

**Comment by raveit65** [comment]
I don't use opera for myself (not available in fedora), so i can only testing possible regressions.

**Comment by snaiperskaya96** [comment]
You can find the RPM package here actually :)
http://www.opera.com/download/get/?partner=www&opsys=Linux&package=RPM

2017-08-08 19:42 GMT+01:00 raveit65 <notifications@github.com>:

**Comment by raveit65** [comment]
An how can i trigger a notification from opera?

**Comment by raveit65** [comment]
Providing steps to reproduce and testing would be great.

**Comment by snaiperskaya96** [comment]
Have a look here ( https://davidwalsh.name/demo/notifications-api.php ),
just click on Show a notification and you will notice the freeze only when
using opera :)

2017-08-08 19:46 GMT+01:00 raveit65 <notifications@github.com>:

**Comment by raveit65** [comment]
Confirmed, that using https://davidwalsh.name/demo/notifications-api.php from opera causes a high cpu usage, but not with firefox. Chrome or chromium seems are using their own notification process, no m-n-d is running here.

**Comment by raveit65** [comment]
I can confirm that using your commit fixes the the issue with opera.
Need to wait for a notification from abrt (fedora bug reporting tool) which use a pie as timing graphic.
Which was mentioned in https://github.com/mate-desktop/mate-notification-daemon/issues/113#issuecomment-320935115
```
The daemon does no more hang, but there is no more sand-glass, that indicates the remaining time. (I use the Nodoka theme.)
```

**Comment by snaiperskaya96** [comment]
Hi! 
Fixed it. The countdown is back.
Please note that the name of the pr is misleading. The cause of this problem is a leak given by the way the pie used to be draft. I rewrote it and seems to work correctly. 
Test it and let me know.

Cheers

**Comment by snaiperskaya96** [comment]
Okay just realised that the opera issue and the countdown one weren't related 😄  Will merge the two fixes as soon as i have time

**Comment by snaiperskaya96** [comment]
Ignore my previous theories. I came to the conclusion that the problem was due to opera setting the timeout to MAX_INT instead of 0 to make an endless notification, i think. Should be definitely fixed now.

**Comment by raveit65** [comment]
Thank you.

**Pull request merged**
