### PR TITLE
GTK3 daemon: fix deprecated gdk_display_get_pointer

### PR DESCRIPTION
**Pull request by raveit65**
inspired from:
https://git.gnome.org/browse/notification-daemon/patch/?id=9f376d3

### CODE REVIEW

**Comment by raveit65** [comment]
@GiedriusS 
indentation are fixed. Did you test the PR?
If you say it's OK, than i will merge it to have it in 1.12

**Comment by GiedriusS** [comment]
Works for me :) We really should start working on fixing gtk3 notifications, though

**Comment by GiedriusS** [comment]
Works for me :) We really should start working on fixing gtk3 notifications, though

**Comment by raveit65** [comment]
Of course, i see the gtk3 notifications every day as i'm using gtk3 mate for production ;)

**Pull request merged**
