### PR TITLE
Some simple daemon.c changes

### PR DESCRIPTION
**Pull request by GiedriusS**
One portability change and one cleanup patch

### CODE REVIEW

**Comment by infirit** [comment]
If I am not mistaken, the int where set to one (1) so shouldn't we set the gbooleans to TRUE?

**Comment by GiedriusS** [comment]
That ":1" is the syntax for defining bitfields in structs, it doesn't set the default value. Where ->has_timeout or ->paused are changed it already uses TRUE/FALSE. Check 6.7.2.1 "Structure and union specifiers" of C99.

**Comment by infirit** [comment]
You are right I misread, thanks :smile:. Looks fine to me otherwise.

**Comment by monsta** [comment]
Why nonnull checks only in these two places?
Also, failed asserts lead to app termination, are you sure it's needed here? There's ```g_return_if_fail``` for less radical behavior.

**Comment by GiedriusS** [comment]
This isn't the only place, search for "assert". Anyway, the whole program needs a lot more NULL checking (not necessarily assertions) before derefencing them and this is a start for that. I think assertions are okay here because adding or removing a timeout is essential for the daemon to quit in time properly.

**Comment by monsta** [comment]
LOL, so that's where bit fields got in:
https://git.gnome.org/browse/notification-daemon/commit/?id=c43d398b26111ca91c5a703858616edd4b7c3bc2

a huge amount of RAM is saved, yeah :laughing:

**Comment by infirit** [comment]
Merged, thanks.

**Pull request closed without merging**
