### PR TITLE
daemon: fix memory leak in on_popup_location_changed()

### PR DESCRIPTION
**Pull request by GiedriusS**
Don't forget to free the result of g_settings_get_string(). Also, change
`slocation' to proper type gchar* for storing results of
g_settings_get_string(). Furthermore, this allows to use that pointer in free()
without any casting.

### CODE REVIEW

**Comment by monsta** [comment]
```const``` can still be used in declaration of ```get_stack_location_from_string```, no?

**Comment by GiedriusS** [comment]
It could but what would be the point of that? To indicate that get_stack_location_from_string() shouldn't touch the argument?

**Comment by monsta** [comment]
Yes. It's not major, just wondering why this change got here too. :smile:

**Comment by GiedriusS** [comment]
I changed because I thought it accepted an `const char *' argument because that was the original type of `slocation' and didn't even think of that reason. I suppose I could fix this in a minute.

**Comment by monsta** [comment]
Squashed and merged in https://github.com/mate-desktop/mate-notification-daemon/commit/75a97c0721b36ee3aafb33b0daed60a0348072f2, thanks :smile:

**Pull request closed without merging**
