### PR TITLE
Add support for GNotification

### PR DESCRIPTION
**Pull request by kajzersoze**

### CODE REVIEW

**Comment by raveit65** [comment]
Can you provide a test case please?

**Comment by kajzersoze** [comment]
https://developer.gnome.org/GNotification/

Thing is, notification will show but without icon, with this commit icon will show.
image_data and image_path are deprecated, see here : https://developer.gnome.org/notification-spec/
But we leave them because libnotify is still using those.
Many apps are using GNotification, you can try to compile sample code from the first link or the code from here and see for yourself that it's not working : http://stackoverflow.com/questions/27341087/glib-gnotification-doesnt-show-icon

**Comment by raveit65** [comment]
I only asked because with providing a quick test case in general for PRs we can test all faster.
Don't forget, only 2 ppls do the reviews at the moment.
Thx, i will look into it.

**Comment by kajzersoze** [comment]
Sure, no problem, I understand.
It was my mistake not to describe the problem in the first place.

**Comment by kajzersoze** [comment]
To save you time and trouble here's my code I was using to test this :
http://www.hastebin.com/cebalesafo.avrasm

or if you don't wanna mess with your custom images a simpler version using themed icon :
http://www.hastebin.com/jaqusukazi.avrasm

In any case, you will see that icon doesn't show and that it shows with this commit.

**Comment by raveit65** [comment]
Does what it promised, thank you.

**Comment by monsta** [comment]
It seems to me that the second part of commit adds already existing code...

**Comment by kajzersoze** [comment]
I'm not sure what you mean by that, first part adds image-data hint and second part adds image-path hint, those were not in the code before.
Can you point to that existing code ?

**Comment by monsta** [comment]
Ah... I mixed ```image_path``` and ```image-path```, sorry. :smile:

**Comment by kajzersoze** [comment]
np :)

**Pull request merged**
