### PR TITLE
wayland: do not attempt to connect to x11 screensaver

### PR DESCRIPTION
**Pull request by lukefromdc**
Fix
https://github.com/mate-desktop/mate-notification-daemon/issues/216

### CODE REVIEW

**Comment by lukefromdc** [comment]
Stopped this warning on sending a notification to m-n-d and allows it to keep going after a suspend to ram:

`** (mate-notification-daemon:6139): WARNING **: 21:58:47.966: Failed to get dbus connection: Error calling StartServiceByName for org.mate.ScreenSaver: Process org.mate.ScreenSaver exited with status 1
`

**Comment by raveit65** [comment]
This fixes the issue in wayland session. 
During testing i noticed that  x11 session isn't locked by mate-screensaver after suspend/hibernate.
After hard testing and 20-30 restarts i found out that mate-session-manager is the culprit. Something between mate-session-manager-1.27.0 and current master do break the lock-screen.
So, please wait with merging until we know whats going on.

**Review by raveit65 — APPROVED** [review]
LGTM,
it  removes the dbus call to mate-screensaver if not in x11 session.

**Comment by zhuyaliang** [comment]
> Should i simple revert commit or does someone wants to look at it?

@raveit65 I think we can open the issue in ```mate-session-`manager```. I will fix it when there is plenty of time

**Comment by raveit65** [comment]
Done https://github.com/mate-desktop/mate-session-manager/issues/308

**Comment by raveit65** [comment]
This commit is unrelated to suspend/hibernate issue with x11.
Should i merge it or is there another reviewer?

**Comment by raveit65** [comment]
I like to do a new release, so merging this PR.

**Pull request merged**
