### PR TITLE
applet: Resize icon size with panel

### PR DESCRIPTION
**Pull request by vkareh**
Also render as scaled cairo surface to support HiDPI displays.

### CODE REVIEW

**Comment by rbuj** [comment]
New warnings:
```
mate-notification-applet.c:184:21: warning: assignment to 'GtkImage *' {aka 'struct _GtkImage *'} from incompatible pointer type 'GtkWidget *' {aka 'struct _GtkWidget *'} [-Wincompatible-pointer-types]
mate-notification-applet.c:185:21: warning: assignment to 'GtkImage *' {aka 'struct _GtkImage *'} from incompatible pointer type 'GtkWidget *' {aka 'struct _GtkWidget *'} [-Wincompatible-pointer-types]
mate-notification-applet.c:189:38: warning: passing argument 1 of 'gtk_widget_set_tooltip_text' from incompatible pointer type [-Wincompatible-pointer-types]
mate-notification-applet.c:190:38: warning: passing argument 1 of 'gtk_widget_set_tooltip_text' from incompatible pointer type [-Wincompatible-pointer-types]
mate-notification-applet.c:192:44: warning: passing argument 2 of 'gtk_box_pack_start' from incompatible pointer type [-Wincompatible-pointer-types]
mate-notification-applet.c:194:44: warning: passing argument 2 of 'gtk_box_pack_start' from incompatible pointer type [-Wincompatible-pointer-types]
mate-notification-applet.c:187:36: warning: passing argument 2 of 'applet_draw_icon' makes integer from pointer without a cast [-Wint-conversion]
mate-notification-applet.c:143:10: warning: conversion to 'gint' {aka 'int'} from 'guint' {aka 'unsigned int'} may change the sign of the result [-Wsign-conversion]
```

**Comment by rbuj** [comment]
New sign conversion warnings:
```
mate-notification-applet.c:149:60: warning: conversion to 'gint' {aka 'int'} from 'guint' {aka 'unsigned int'} may change the sign of the result [-Wsign-conversion]
mate-notification-applet.c:153:61: warning: conversion to 'gint' {aka 'int'} from 'guint' {aka 'unsigned int'} may change the sign of the result [-Wsign-conversion]
```
https://developer.gnome.org/gtk3/stable/GtkIconTheme.html#gtk-icon-theme-load-surface
```diff
diff --git a/src/capplet/mate-notification-applet.c b/src/capplet/mate-notification-applet.c
index 1f349d9..71f11c6 100644
--- a/src/capplet/mate-notification-applet.c
+++ b/src/capplet/mate-notification-applet.c
@@ -146,11 +146,11 @@ applet_draw_icon (MatePanelApplet *applet_widget,
 
   cairo_surface_t *image_on = gtk_icon_theme_load_surface (gtk_icon_theme_get_default (),
                                                            "user-available",
-                                                           size, scale,
+                                                           (gint) size, scale,
                                                            NULL, 0, NULL);
   cairo_surface_t *image_off = gtk_icon_theme_load_surface (gtk_icon_theme_get_default (),
                                                             "user-invisible",
-                                                            size, scale,
+                                                            (gint) size, scale,
                                                             NULL, 0, NULL);
 
   gtk_image_set_from_surface (GTK_IMAGE (applet->image_on), image_on);
```

**Comment by raveit65** [comment]
Btw. I get an abrt alarm when i restart the panel with `killall mate-panel` (master branch)
https://github.com/mate-desktop/mate-notification-daemon/issues/189

**Review by rbuj — APPROVED** [review]
LGTM

**Comment by rbuj** [comment]
> Btw. I get an abrt alarm of m-n-d when i restart the panel with `killall mate-panel` (master branch)
> #189

PR #190

**Review by lukefromdc — COMMENTED** [review]
I just tested this, replacing my (poorly suited and until now unused) user-available and user-invisible icons with the high-res ones I first saw in playing around with the 2010-era, then-experimental version of gnome-shell. I never forgot that ghost, and with this commit the ghost and human-form with green electrical trace render sharp and clear, scaling with the panel. Without it, they render at a fixed size regardless of panel size. This is using a single scalable .svg icon for each.

We do need to fix that abrt on restarting the panel reported by another tester ( I get a segfault on killing the applet with this), but other than that I have it working. I do NOT get that segfault with master after the latest commit there

**Review by lukefromdc — APPROVED** [review]
Rebasing this against master to apply
https://github.com/mate-desktop/mate-notification-daemon/commit/661e3b47834b5e794947d837cd98bbddbea1ad53
(which this predates) stops the segfaults. Approving as it will have to be rebased to merge anyway

**Pull request merged**
